ASP.NET MVC Diploma/Diplom_project/Controllers/WebStoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Diplom_project.Models;

namespace Diplom_project.Controllers
{
    public class WebStoreController : Controller
    {
        //
        // GET: /WebStore/

        private mydbEntities webstoreDB = new mydbEntities();
        public static List<string> productTypes = new List<string>() { "Браслети", "Брелоки", "Кольє", "Кільця жіночі", "Кільця обручальні", "Чоловічі вироби", "Сережки" };
        //
        // GET: /Store/

        public ActionResult Index()
        {

            return View(productTypes);
        }

        //
        // GET: /Store/Browse?genre=Disco

        public ActionResult Browse(string type)
        {
            List<Product> tmplist = webstoreDB.product.ToList();
            List<Product> productList = tmplist.Where(p => p.typeProduct == type).ToList();
            // Retrieve Genre and its Associated Albums from database

            return View(productList);
        }

        public ActionResult DetailsGems(int idProd)
        {
            List<Gemsinprod> gemList = webstoreDB.gemsinprod.Where(p => p.Product_idProduct == idProd).ToList();
            foreach (var gemitem in gemList)
            {
                if(gemitem.gem==null)
                    gemitem.gem = webstoreDB.gem.Single(p => p.idGem == gemitem.Gem_idGem);
            }
            // Retrieve Genre and its Associated Albums from database

            return PartialView(gemList);
        }
        //
        // GET: /Store/Details/5

        public ActionResult Details(int id)
        {
            var product = webstoreDB.product.Find(id);
            return View(product);
        }

        //
        // GET: /Store/GenreMenu

        [ChildActionOnly]
        public ActionResult ProductTypeMenu()
        {
            return PartialView(productTypes);
        }

    }
}

ASP.NET MVC Diploma/Diplom_project/Views/WebStore/Browse.cshtml
@model List<Diplom_project.Product>
@{
    
    ViewBag.Title = "Browse Albums";
}
 
<div class="genre">
    <h3><em> @if(Model.Count!=0){
         @Model.ElementAt(0).typeProduct}</em></h3>
<div class="center">
        @foreach (var product in Model)
        {
            <div>
                <a class="product_img_link" href="@Url.Action("Details", new { id = product.idProduct })">
                    <img alt="@product.nameProduct" class="img-rounded" src="/Content/Images/@product.imageName" />
                    <h3>@product.nameProduct
                    <span class="price" style="display:inline;">@product.price грн.</span>
                    </h3>
                </a>
            </div>
        }
    </div>
</div>

ASP.NET MVC Diploma/Diplom_project/Views/WebStore/Details.cshtml
@model Diplom_project.Product
@{
    ViewBag.Title = "Виріб - " + Model.nameProduct;
}

<h2>@Model.nameProduct</h2>

<p>
    <img alt="@Model.nameProduct" class="img-rounded" src="/Content/Images/@Model.imageName" />
</p>

<div id="album-details">
    <p>
        <em>Тип:</em>
        @Model.typeProduct
    </p>
    <p>
        <em>Матеріал:</em>
        @Model.material.nameMaterial проба @Model.material.probe
    </p>
    <p>
        <em>Дорогоцінне каміння:</em>
         @{Html.RenderAction("DetailsGems", "WebStore", new { idProd = Model.idProduct });}
    </p>
    <p class="button">
        @Html.ActionLink("Add to cart", "AddToCart", 
        "ShoppingCart", new { id = Model.idProduct }, "")
    </p>
</div>

ASP.NET MVC Diploma/Diplom_project/Views/WebStore/DetailsGems.cshtml
@model List<Diplom_project.Gemsinprod>
<div id="album-details">
@if (Model.Count != 0)
{
     foreach (var item in Model)
        {
         <p>
                @item.gem.nameGem :
         </p>
               <p>
                @item.amount шт. @item.gem.weightGem карат., @item.gem.infoGem , @item.gem.formGem 
            </p>
       
        }
}
else
{
      <p>Немає дорогоцінного каміння </p>
}
</div>

ASP.NET MVC Diploma/Diplom_project/Views/WebStore/Index.cshtml
@model List<string>
@{
    ViewBag.Title = "Store";
}
<h3>Browse Genres</h3>

<p>
    Select from @Model.Count() genres:</p>
<ul>
    @foreach (var product in Model)
    {
        <li>@Html.ActionLink(product, "Browse", new {type = product})</li>
    }
</ul>

ASP.NET MVC Diploma/Diplom_project/Views/WebStore/ProductTypeMenu.cshtml
@model List<string>

<ul class="nav nav-pills nav-stacked">
    @foreach (var product in Model)
    {
        <li>@Html.ActionLink(product, 
                "Browse", "WebStore", 
                new { type = product }, null)
        </li>
    }
</ul>